apiVersion: apps/v1
kind: Deployment
metadata:
  name: "micronaut-test"
spec:
  selector:
    matchLabels:
      app: "micronaut-test"
  template:
    metadata:
      labels:
        app: "micronaut-test"
    spec:
      containers:
        - name: "micronaut-test"
          image: "gcr.io/micronaut-test/jib-image"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "micronaut-test"
spec:
  selector:
    app: "micronaut-test"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080