---
micronaut:
    application:
        name: com.ajaymdesai.micronaut-test
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: ${application.api.swagger.path}/**
---
micronaut:
    ssl:
        enabled: fals
        buildSelfSigned: true
---
micronaut:
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
        token:
            basic-auth:
                enabled: true
---
micronaut:
    http:
        services:
            books:
                urls:
                    - "http://localhost:8011"
---
application:
    api:
        swagger:
            path: /api-docs/swagger
            version: 3.22.0
            layout: StandaloneLayout
            deepLinking: true
            urls:
                - name: micronaut-test
                  url: /api-docs/swagger/com.ajaymdesai.micronaut-test-1.0.yml
