---
micronaut:
  application:
    name: micronaut-test

---
micronaut:
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: false
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:secret}"
